r second period class? "))
Period3 = int(input("What is your grade in your third period class? "))
Period4_or_5 = int(input("What is your grade in your fourth or fifth period class? "))
Period6 = int(input("What is your grade in your sixth period od class? "))
Period7 = int(input("What is your grade in your seventh period class? "))
Period8 = int(input("What is your grade in your eigth period class? "))
grade_average = float((Period1+Period2+Period3+Period4_or_5+Period6+Period7+Period8)/7)
print("Your grade average is")
print(round(grade_average, 2))
