# BHR 2nd turtle race
import turtle 
import random turtle1 = turtle.Turtle() 
turtle2 = turtle.Turtle() 
turtle3 = turtle.Turtle() 
turtle4 = turtle.Turtle() 
turtle5 = turtle.Turtle() 
turtle6 = turtle.Turtle() 
turtle1.speed(random.randint(0,10)) # 1:slowest, 3:slow, 5:normal, 10:fast, 0:fastest 
turtle2.speed(random.randint(0,10)) 
turtle3.speed(random.randint(0,10)) 
turtle4.speed(random.randint(0,10)) 
turtle5.speed(random.randint(0,10)) 
turtle6.speed(random.randint(0,10)) 
turtle1.shape("turtle") 
turtle2.shape("turtle") 
turtle3.shape("turtle") 
turtle4.shape("turtle") 
turtle5.shape("turtle") 
turtle6.shape("turtle") 
turtle1.color("blue") 
turtle2.color("teal") 
turtle3.color("green") 
turtle4.color("orange") 
turtle5.color("red") 
turtle6.color("black") 
turtle2.setposition(0, 20) 
turtle3.teleport(0, 40) 
turtle4.teleport(0, 60) 
turtle5.teleport(0, -20) 
turtle6.teleport(0, -40) 
turtle1.forward(250) 
turtle2.forward(250) 
turtle3.forward(250) 
turtle4.forward(250) 
turtle5.forward(250) 
turtle6.forward(250)
